/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package eu.busi.myplanning.api.controllers;

import com.fasterxml.jackson.databind.ObjectMapper;
import eu.busi.myplanning.api.models.UserDTO;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-09-17T09:37:55.101969900+02:00[Europe/Berlin]")
@Api(value = "user", description = "the user API")
public interface UserApi {

    Logger log = LoggerFactory.getLogger(UserApi.class);

    Optional<ObjectMapper> getObjectMapper();

    Optional<HttpServletRequest> getRequest();

    

    @ApiOperation(value = "", nickname = "deleteUser", notes = "", response = Boolean.class, tags={ "User API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Boolean.class) })
    @RequestMapping(value = "/user/{id}",
        produces = { "*/*" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Boolean> deleteUser(@ApiParam(value = "",required=true) @PathVariable("id") Long id
);


    @ApiOperation(value = "", nickname = "findUser", notes = "", response = Object.class, tags={ "User API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Object.class) })
    @RequestMapping(value = "/user/{idOrUsernameOrEmail}",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> findUser(@ApiParam(value = "",required=true) @PathVariable("idOrUsernameOrEmail") String idOrUsernameOrEmail
);


    @ApiOperation(value = "", nickname = "findUsersByOrganization", notes = "", response = Object.class, tags={ "User API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Object.class) })
    @RequestMapping(value = "/user/organization/{organization}",
        produces = { "*/*" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> findUsersByOrganization(@ApiParam(value = "",required=true) @PathVariable("organization") String organization
);


    @ApiOperation(value = "", nickname = "saveUser", notes = "", response = Object.class, tags={ "User API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = Object.class) })
    @RequestMapping(value = "/user",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Object> saveUser(@ApiParam(value = "" ,required=true )  @Valid @RequestBody UserDTO body
);


    @ApiOperation(value = "", nickname = "updateUser", notes = "", response = Object.class, tags={ "User API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Object.class) })
    @RequestMapping(value = "/user/{id}",
        produces = { "*/*" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Object> updateUser(@ApiParam(value = "" ,required=true )  @Valid @RequestBody UserDTO body
,@ApiParam(value = "",required=true) @PathVariable("id") Long id
);

}
