logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
server:
  port: 8081
spring:
  datasource:
    password: myplanning
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    url: jdbc:mysql://localhost:3306/my-planning?useTimezone=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: myplanning
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      encoding: UTF-8
      mode: always
springdoc:
  api-docs:
    path: /myplanning-doc
  packages-to-scan: eu.busi.myplanning.domain