openapi: 3.0.3

info:
  title: MyPlanning API
  description: Voiçi l'API pour l'application MyPlanning
  version: 1.0.0

servers:
  - url: https://localhost:8081/
    description: where you can use the api

tags:
  - name: "Agenda API"
  - name: "Auth API"

paths:

  /agenda:
    get:
      tags:
        - "Agenda API"
      summary: Get all agendas
      description: This returns all the agendas
      operationId: find
      responses:
        "200":
          description: returned a value
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./api/models/agendaDTO.yaml"
        "400":
          description: BAD_REQUEST
        "401":
          description: UNAUTHORIZE
    post:
      tags:
        - "Agenda API"
      summary: Create an agenda
      description: This returns the created agenda
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./api/models/agendaDTO.yaml"
      responses:
        "200":
          description: returned a value
          content:
            application/json:
              schema:
                $ref: "./api/models/agendaDTO.yaml"
        "400":
          description: BAD_REQUEST
        "401":
          description: UNAUTHORIZE

  /agenda/{id}:
    get:
      tags:
        - "Agenda API"
      summary: Get agenda
      description: This returns an agenda from an id
      operationId: findById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the user to get
      responses:
        "200":
          description: returned a value
          content:
            application/json:
              schema:
                $ref: "./api/models/agendaDTO.yaml"
        "400":
          description: BAD_REQUEST
        "401":
          description: UNAUTHORIZE
    delete:
      tags:
        - "Agenda API"
      summary: Delete an agenda
      description: This returns true or false if the agenda has been deleted
      operationId: delete
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the user to get
      responses:
        "200":
          description: returned a value
          content:
            application/json:
              schema:
                type: boolean
        "400":
          description: BAD_REQUEST
        "401":
          description: UNAUTHORIZE

  /agenda/user/{id}:
    get:
      tags:
        - "Agenda API"
      summary: Get agendas by user
      description: This returns an agenda from an id
      operationId: findByUser
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the user to get
      responses:
        "200":
          description: returned a value
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./api/models/agendaDTO.yaml"
        "400":
          description: BAD_REQUEST
        "401":
          description: UNAUTHORIZE

  /agenda/shared/user/{id}:
    get:
      tags:
        - "Agenda API"
      summary: Get sharedAgendas by user
      description: This returns shared agendas from a user id
      operationId: findSharedAgendasByUser
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the user to get
      responses:
        "200":
          description: returned a value
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./api/models/agendaDTO.yaml"
        "400":
          description: BAD_REQUEST
        "401":
          description: UNAUTHORIZE

  /auth/login:
    post:
      tags:
        - "Auth API"
      summary: Login
      description: This will connect the user and generate a jwt token
      operationId: login
      responses:
        "200":
          description: returned a value
          content:
            application/json:
              schema:
                type: string
        "400":
          description: BAD_REQUEST
        "401":
          description: UNAUTHORIZE

components:
  schemas:
    $ref: "./api/models/_schema.yaml"
